options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/mlops-nuclio-022025/ds-market/sales-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/mlops-nuclio-022025/ds-market/sales-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sales-api'
      - '--image'
      - 'europe-west1-docker.pkg.dev/mlops-nuclio-022025/ds-market/sales-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--port'
      - '8080'
      - '--timeout'
      - '600'
      - '--allow-unauthenticated'
      - '--vpc-connector'
      - 'dsmarket-conector'
      - '--vpc-egress'
      - 'all-traffic'
      - '--set-env-vars'
      - |
        ALLOYDB_USER=postgres,
        ALLOYDB_PASSWORD=*market_9991,
        ALLOYDB_HOST=34.175.172.72,
        ALLOYDB_PORT=5432,
        ALLOYDB_DB=dsmarket
